[WIP] Indexview and SignView
asv-NgocTT/djangoapp pull request #1
Opened 2017-05-03 07:51 UTC by asv-NgocTT

Indexview and SignView
-----------------
Start date: 28-4-2017
End date: 2-5-2017

2017-05-03 11:08 UTC, asv-thanglna commented on guestbook/urls.py
> +
comment thì xox đi.

2017-05-03 11:09 UTC, asv-thanglna commented on templates/guestbook/sign_page.html
> +{#      <input type="hidden" name="guestbook_name" value="{{ guestbook_name }}" />#}
xoá comment

2017-05-03 11:10 UTC, asv-thanglna commented on templates/guestbook/template.html
> +</html>
để 1 line trống cuối file.

2017-05-04 07:13 UTC, vn-trinhtk requested changes
@asv-NgocTT

2017-05-04 07:13 UTC, vn-trinhtk commented on guestbook/admin.py
> +
ko dùng thì xoá

2017-05-04 07:13 UTC, vn-trinhtk commented on guestbook/forms.py
> +class RegisterForm(forms.Form):
`RegisterForm` → `SignForm`

2017-05-04 07:13 UTC, vn-trinhtk commented on guestbook/tests.py
> +
xoá file thừa này giúp a

2017-05-04 07:13 UTC, asv-trinhtk commented on guestbook/views.py
> +from guestbook.models import Greeting, guestbook_key, DEFAULT_GUESTBOOK_NAME
check xem module nào thừa thì xoá ra

2017-05-04 07:13 UTC, asv-trinhtk commented on guestbook/views.py
> +		# cach lay gia tri trongform
ko dùng comment = tiếng việt nhé

2017-05-04 07:13 UTC, asv-trinhtk commented on guestbook/views.py
> +		greeting.put()
thao tác push phải đưa vào transaction.

2017-05-04 07:53 UTC, vn-trinhtk requested changes
@asv-NgocTT

2017-05-04 07:53 UTC, asv-trinhtk commented on guestbook/views.py
> +	@ndb.transactional
sử dụng transactional sai, đọc kỹ lại, hiểu rõ rồi sử dụng lại cho đúng

2017-05-04 07:53 UTC, asv-trinhtk commented on guestbook/views.py
> +from django.http import HttpResponse,HttpResponseRedirect
check xem import module nào thừa thì xoá

2017-05-04 07:53 UTC, asv-trinhtk commented on guestbook/views.py
> +		# how to get velue in the form
fix typo

2017-05-04 07:53 UTC, asv-trinhtk commented on guestbook/views.py
> +class IndexView(TemplateView):
trước class phải cách 2 line

2017-05-04 07:53 UTC, asv-trinhtk commented on guestbook/views.py
> +from django.http import HttpResponse,HttpResponseRedirect
sort thứ tự module:
- django.core 
- django 

- google.appengine 

- guestbook

2017-05-04 07:53 UTC, asv-trinhtk commented on guestbook/mail.py
> +send_mail('Subject here', 'Here is the message.', 'from@example.com', ['to@example.com'], fail_silently=False)
file này ko ổn

2017-05-04 07:53 UTC, asv-trinhtk commented on guestbook/views.py
> +	def send_email(self,request):
function cách function 1 line.
cách class mới 2 lines

2017-05-04 07:53 UTC, asv-trinhtk commented on settings.py
> +EMAIL_USE_TLS = True
những cái này ko cần thiết, dùng hàm gửi mail của google app engine

2017-05-04 07:53 UTC, asv-trinhtk commented on guestbook/views.py
> +		greetings = greetings_query.fetch(10)
fetch 10 cái, nếu lớn hơn 10 cái thì sao ? ko load đc tiếp ?

2017-05-04 07:53 UTC, asv-trinhtk commented on guestbook/views.py
> +		greeting.put()
sau khi put greeting, thì send mail thông báo cho admin của page

2017-05-08 02:23 UTC, vn-trinhtk requested changes

2017-05-08 02:23 UTC, asv-trinhtk commented on guestbook/forms.py
> +from django import forms
Thêm `# -*- coding: utf-8 -*-`

2017-05-08 02:23 UTC, asv-trinhtk commented on guestbook/models.py
> +from google.appengine.ext import ndb
Thêm `# -*- coding: utf-8 -*-`

2017-05-08 02:23 UTC, asv-trinhtk commented on guestbook/urls.py
> +from django.conf.urls import url
Thêm `# -*- coding: utf-8 -*-`

2017-05-08 02:23 UTC, asv-trinhtk commented on guestbook/views.py
> +from django.core.urlresolvers import reverse_lazy
Thêm `# -*- coding: utf-8 -*-`

2017-05-08 02:23 UTC, asv-trinhtk commented on guestbook/apps.py
> +    name = 'guestbook'
dùng tab indent, ko dùng space indent. Fix tất cả file.

2017-05-08 02:23 UTC, asv-trinhtk commented on guestbook/apps.py
> +from __future__ import unicode_literals
ko dùng thì xoá

2017-05-08 02:23 UTC, asv-trinhtk commented on guestbook/forms.py
> +    content=forms.CharField(label='Content', widget=forms.Textarea, max_length=10)
"no newline at end of file "

2017-05-08 02:23 UTC, asv-trinhtk commented on guestbook/models.py
> +class Greeting(ndb.Model):
trước class, cách 2 line

2017-05-08 02:23 UTC, asv-trinhtk commented on guestbook/views.py
> +	# def send_email(self,request):
k dùng thì xoá

2017-05-09 07:05 UTC, asv-thanglna commented on guestbook/forms.py
> +    content=forms.CharField(label='Content', widget=forms.Textarea, max_length=100)
thêm 1 line trống cuối file

2017-05-09 07:06 UTC, asv-thanglna commented on guestbook/taskmail.py
> +], debug=True)
file này dùng làm gì vậy???

2017-05-09 07:06 UTC, asv-thanglna commented on guestbook/urls.py
> +]
thêm 1 line trống cuối file

2017-05-09 07:07 UTC, asv-thanglna commented on guestbook/viewss/sendMail.py
> +       body=sender + content)
thêm 1 line trống cuối file. khách function với import là 2 lines

2017-05-09 07:08 UTC, asv-thanglna commented on guestbook/viewss/taskqueue_mail.py
> +], debug=True)
thêm 1 line trống cuối file. khách function với import là 2 lines

2017-05-09 07:08 UTC, asv-thanglna commented on guestbook/worker.py
> +    ('/update_counter', UpdateCounterHandler)
file này làm ji vậy????

2017-05-09 07:09 UTC, asv-thanglna commented on templates/guestbook/main_page.html
> -</html></html>
ko để line trống ở giữa.

2017-05-09 07:10 UTC, asv-thanglna commented on templates/guestbook/sign_page.html
> +
ko để line trống ở giữa,
1 line trống ở cuối file.

2017-05-09 07:10 UTC, asv-thanglna commented on templates/guestbook/template.html
> +
ko để line trống ở giữa,
1 line trống ở cuối file.

2017-05-09 07:14 UTC, asv-thanglna commented on guestbook/viewss/signView.py
> +		taskqueue_mail.add_task(greeting.author.email(), content)
chưa check trường hợp user chưa login.

2017-05-09 10:30 UTC, asv-thanglna commented on guestbook/views/signView.py
> +			functionput()
chỗ này: user chưa login thì ko put vào db, ko gửi mail sao???
xem lại chỗ này.

2017-05-09 10:31 UTC, asv-thanglna commented on guestbook/views/signView.py
> +	def post(self, request, *args, **kwargs):
hàm nào ko thay đổi từ thằng cha, thì ko cần viết lại.
xem lại def post(self, request, *args, **kwargs)

2017-05-10 03:41 UTC, merged

2017-05-10 04:05 UTC, asv-thanglna commented on guestbook/views/signView.py
> -	def get_initial(self):
sao lại bỏ hàm get_initial(self)  vậy???

2017-05-10 04:07 UTC, asv-thanglna commented on guestbook/views/signView.py
> +			functionput()
chỗ này sửa tùm lum vậy??? chưa hiểu lắm.

2017-05-10 07:55 UTC, asv-NgocTT commented on guestbook/taskmail.py
> +], debug=True)
em da xoa file nay